# Your Chaturbate username
username: testingallthethings
# Your Chaturbate password, I promise not to do anything bad with it
password: 2YY84bKlOC79KNQ

# Where you want the captures to be saved to
captureDirectory: captures
# Where you want the "finalized" captures to be moved to as soon as model stops streaming
completeDirectory: complete

# In seconds, how often capturebate-node checks for newly-online models
modelScanInterval: 30

# Debugging
debug: false
